### ISSUE TITLE
2.8.5 - unsupported version?

### ISSUE THREAD

**Issue by tilllt** [beanieboi/ffprober#65]
.rvm/gems/ruby-2.1.5@catapeli/gems/ffprober-0.4.6/lib/ffprober/parser.rb:7:in `from_file': no or unsupported ffprobe version found. (version: 2.8.5) (ArgumentError)

looking at the github commits, it seemed to me ffprobe 2.8.5 was support in master?
`ffprobe version 2.8.5 Copyright (c) 2007-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.5 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100`

**Comment by beanieboi** [comment]
hey,

i just released version 0.5.1 which only implements an minimum version check. all future versions of ffmpeg are support now.

let me know if you need further help.

ben
